name: Deploy to staging environment

# Controls when the action will run
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [staging-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-apps-workflow:
    # Replace with repository name
    name: Graasp App Excalidraw
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cdelivery-s3-apps.yml@v1
    # Replace input build-folder or version if needed
    with:
      build-folder: 'build'
      version: 'latest'
      tag: ${{ github.event.client_payload.tag }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
      aws-region: ${{ secrets.APPS_AWS_REGION }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_APPS_STAGE }}
      cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_APPS_STAGE }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain: ${{ secrets.STAGE_GRAASP_DOMAIN }}
      sentry-dsn: ${{ secrets.SENTRY_DSN }}
